apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worldcup-ingress
  labels:
    app: worldcup-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: worldcup-app
                port:
                  number: {{ .Values.service.port }}
