apiVersion: v1
kind: Service
metadata:
  name: worldcup-postgres
  labels:
    app: worldcup-postgres
spec:
  clusterIP: None  # Headless service pour le StatefulSet
  selector:
    app: worldcup-postgres
  ports:
    - port: 5432
      targetPort: 5432
