apiVersion: v1
kind: Service
metadata:
  name: worldcup-postgres
  labels:
    app: worldcup-postgres
spec:
  clusterIP: None  # Headless service pour le StatefulSet
  selector:
    app: worldcup-postgres
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
